name: Unit Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit testing REST API
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
