name: Unit Testing

on:
  push:
    branches:
      - main

jobs:
  unittest:
    name: Unit testing REST API
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./
      
      - name: Run tests
        run: |
          pytest
  
  integration-test:
    needs: unittest
    name: DB Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./
      
      - name: Start API Server
        run: |
          python3 -m app.integration_tests.db_test
  deploy:
    needs: integration-test
    name: deploy development version
    runs-on: ubuntu-latest

    steps:
      - name: cleanup
        run: |
          rm -rf ~/.ssh

      - name: install ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_IP }} > ~/.ssh/known_hosts

      - name: connect and pull
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }} "cd ${{ secrets.TARGET_DIR }} && git pull"

      # use it when server is not running
      - name: build app
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }} "cd ${{ secrets.TARGET_DIR }} && docker build -t globant-code-challenge ."
      
      - name: stop container
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }} "if (( docker rm -f codechallengeapi )); then echo 'Failed to stop container'; fi"

      
      # Start 
      - name: run the container
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }} "docker run -p 4000:4000 -d --name codechallengeapi --network host globant-code-challenge"
  
