name: Unit Testing

on:
  push:
    branches:
      - main

jobs:
  unittest:
    name: Unit testing REST API
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./
      
      - name: Run tests
        run: |
          pytest
  
  integration-test:
    name: DB Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./
      
      - name: Start API Server
        run: |
          python3 -m app.integration_tests.db_test
  
